export const CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD";
export const REQUEST_GIPHY_PENDING = "REQUEST_GIPHY_PENDING";
export const REQUEST_GIPHY_SUCCESS = "REQUEST_GIPHY_SUCCESS";
export const REQUEST_GIPHY_FAILED = "REQUEST_GIPHY_FAILED";

export const REQUEST_GIPHY_SEARCH_NEW = "REQUEST_GIPHY_SEARCH_NEW";
export const REQUEST_GIPHY_SEARCH_LAZY = "REQUEST_GIPHY_SEARCH_LAZY";
export const REQUEST_GIPHY_SEARCH_PENDING = "REQUEST_GIPHY_SEARCH_PENDING";
export const REQUEST_GIPHY_SEARCH_SUCCESS = "REQUEST_GIPHY_SEARCH_SUCCESS";

export const GET_HISTORY = "GET_HISTORY";
export const SET_HISTORY = "SET_HISTORY";
export const GET_HISTORY_LOCAL = "SET_HISTORY_LOCAL";
